WITH RENTAL_COUNT AS (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
),
MONTHLY_RECORDS AS (
    SELECT 
        EXTRACT(MONTH FROM START_DATE) AS MONTH,
        CAR_ID,
        COUNT(*) AS RECORDS
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY EXTRACT(MONTH FROM START_DATE), CAR_ID
)
SELECT 
    M.MONTH, 
    M.CAR_ID, 
    M.RECORDS
FROM MONTHLY_RECORDS M
JOIN RENTAL_COUNT R ON M.CAR_ID = R.CAR_ID
ORDER BY M.MONTH ASC, M.CAR_ID DESC;